config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
	root 'map#show'
	post 'saveCircle' => 'map#save'
	get 'signup' => 'users#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :users do
		collection do
			get :autocomplete
		end
	end

	resources :restaurants do
		collection do
			get :autocomplete
		end
	end

	resources :food_reviews

	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	searchkick(autocomplete: [:name], word_start: [:name]) if Rails.env.development?

	has_many :food_reviews, dependent: :destroy
	accepts_nested_attributes_for :food_reviews
	#validates :food_reviews, length: {minimum: 1}
	validates :name, presence: true
	validates :address, presence: true, uniqueness: true
	validate :check_location_validity

	private
		
		def check_location_validity
			if lat == 25.0169826 and lng == 121.4627868
				errors.add(:address, "should be a valid address")
			end
		end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	require 'WEBrick' if Rails.env.development?
	before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
	before_action :admin_user, only: [:edit, :update, :destroy]
		
	def show
		@restaurant = Restaurant.find(params[:id])
		@food_reviews = @restaurant.food_reviews.paginate(page: params[:page])
	end

	def index
		if params[:query].present?
			@restaurants = Restaurant.search(params[:query], fields: [{name: :word_start}])
		else
			@restaurants = Restaurant.all
		end
	end

	def create
		restaurant = Restaurant.new(restaurant_params)
		@food_review = current_user.food_reviews.build(food_review_params)

		query = "http://maps.googleapis.com/maps/api/geocode/json?address=#{restaurant.address}&sensor=false"
		query.force_encoding("binary")
		query=WEBrick::HTTPUtils.escape(query)
		result = JSON.parse(open(query).read)
		restaurant.lat = result["results"][0]["geometry"]["location"]["lat"]
		restaurant.lng = result["results"][0]["geometry"]["location"]["lng"]
		@restaurant = Restaurant.find_by(lat: restaurant.lat, lng: restaurant.lng)

		if !@restaurant
			if restaurant.save
				@food_review.restaurant_id = restaurant.id
				if @food_review.save
					flash[:info] = "Restaurant and Review created!"
					redirect_to restaurant
				else
					render "new"
				end
			else
				render "new"
			end
		else
			@food_review.restaurant_id = @restaurant.id
			if @food_review.save
				flash[:info] = "Review created!"
				redirect_to @restaurant
			else
				render "new"
			end
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update_attributes(restaurant_params)
			flash[:success] = "Restaurant updated"
			redirect_to @Restaurant
		else
			render 'edit'
		end
	end

	def destroy
		Restaurant.find(params[:id]).destroy
		flash[:success] = "Restaurant deleted"
		redirect_to restaurants_url
	end

	def autocomplete
		render json: Restaurant.search(params[:query], fields: [{name: :word_start}]).map(&:name)
	end

	private

		def restaurant_params
			params.require(:restaurant).permit(:name, :address)
		end

		def food_review_params
			params.require(:food_review).permit(:content, :image, :image_cache)
		end

		def admin_user
			redirect_to root_url unless current_user.admin?
		end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_restaurant.html.erb
<li>
	<%= link_to restaurant.name, restaurant, id: "name" %>
	<section>
		<% if current_user.admin? %>
			<%= link_to "delete", restaurant, method: :delete, data: {confirm: "You sure?"} %>
		<% end %>
	</section>
</li>

app/views/restaurants/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= bootstrap_form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save Changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/restaurants/index.html.erb
<%= provide(:title, 'Restaurants') %>
<h1>Restaurants</h1>

<% if Rails.env.development? %>
	<%= form_tag restaurants_path, method: 'get', class: "form-inline" do %>
		<div class="form-group form-custom">
			<%= text_field_tag :query, params[:query], id: "restaurant_search" %>
		</div>

		<%= button_tag(type: "submit", class: "btn btn-primary") do %>
			<span class="glyphicon glyphicon-search"></span>
		<% end %>
		<div class="form-group">
			<%= link_to "Review a restaurant", new_food_review_path, method: :get, 
									class: "btn btn-primary btn-sm", style: "margin-left: 10px; font-size: 18px" %>
		</div>
	<% end %>	
<% end %>

<div class="users">
	<%= render @restaurants %>
</div>

app/views/restaurants/new.html.erb
<% provide(:title, 'New Restaurant') %>
<h1>New Restaurant</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= bootstrap_form_for(@restaurant) do |f| %>
			<%= f.text_field :name %>
			<%= f.email_field :address %>
			<%= fields_for(@restaurant.food_reviews.build) do |u| %>
				<div class="field">
					<%= u.label :Review %>
					<%= u.text_area :content, placeholder: "Compose review...", rows: "4",
													class: "form-control" %>
				</div>
				<span class="picture">
					<%= u.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
					<%= u.hidden_field :image_cache %>
				</span>
			<% end %>
			<%= f.submit "New Restaurant", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<div>
					<%= @restaurant.name %>
				</div>
				<div>
					<%= @restaurant.address %>
				</div>
				<div>
					<%= link_to "Ptt Review", @restaurant.url %>
				</div>
			</h1>
		</section>
	</aside>
	<div class="col-md-8">
		<% if @restaurant.food_reviews.any? %>
			<h3>Food Reviews (<%= @restaurant.food_reviews.count %>)</h3>
			<ol class="microposts">
				<%= render @food_reviews %>
			</ol>
			<%= will_paginate @food_reviews %>
		<% end %>
	</div>
</div>