config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
	root 'map#show'
	post 'saveCircle' => 'map#save'
	get 'signup' => 'users#new'
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

	resources :users do
		collection do
			get :autocomplete
		end
	end

	resources :restaurants do
		collection do
			get :autocomplete
		end
	end

	resources :food_reviews

	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default nav-custom">
	<div class="container">
		<%= link_to "Bike & Bite", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path, id: "menu", data: { no_turbolink: true } %></li>
				<li><%= link_to "Restaurants", restaurants_path, id: "menu" %></li>
				<% if logged_in? %>
					<li><%= link_to "Users", users_path, id: "menu" %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown", id="menu">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu", id="menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete", id: "menu" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign up", signup_path, id: "menu" %></li>
					<li><%= link_to "Log in", login_path, id: "menu" %>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag "application", 
				"//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js",
				'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class = "container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<!--%= render 'layouts/footer' %!-->
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>